### ISSUE TITLE
Can't run benchmarks

### ISSUE THREAD

**Issue by andykenward** [GoodBoyDigital/mini-runner#3]
Following the [#benchmarks](https://github.com/GoodBoyDigital/mini-runner/blob/33449501430fa359f45e6fa189dc0157c3a31b64/README.md#benchmarks) instructions to run the benchmarks results in error of 

```
missing script: start
```

using
macOS `10.12.3`
Node `v6.9.1`
NPM  `v3.10.8`

**Comment by GoodBoyDigital** [comment]
Thanks for the heads up! Forgot to push :) all fixed now 👍
